### ISSUE TITLE
Enhancement - 

### ISSUE THREAD

**Issue by johndpope** [Dev1an/A-Star#1]
Just watched this 
https://youtu.be/gGQ-vAmdAOI?t=171

was thinking of extending some of the classes to handle other use cases. 
![screen shot 2016-11-19 at 8 30 52 am](https://cloud.githubusercontent.com/assets/289994/20455793/8bcb67be-ae32-11e6-8006-a3e157a77f42.png)

**Comment by Dev1an** [comment]
Hi John, feel free to extend and improve my code and to contribute your changes back to the community by submitting a pull request.
What use cases do you want to handle?

**Comment by johndpope** [comment]
hi @Dev1an  - found your inputevents swift project. that's neat. 
not sure if you've come across https://github.com/johnsundell/marathon
going to close this issue as part of spring cleaning exercise. 

Thanks
JP
