### ISSUE TITLE
Cant Run It

### ISSUE THREAD

**Issue by magonicolas** [Dev1an/A-Star#2]
Hello Sorry, for saying this as an issue, but didn't know how tot talk to you, I don't know how to run and test your code, I have dowloaded it, open it on Xcode and click play, but it doesn't open anything(I have iOs experience, but never scene a Xcode project that builds to My Mac )

**Comment by Dev1an** [comment]
- First build the aStar framework (`Product > Build` or `Cmd+B`)
- Then open the playground and show the Assistant editor

Let me know if you still have issues after trying this

**Comment by Dev1an** [comment]
Also have a look at: http://ericasadun.com/2015/03/16/swift-working-around-sources-playground-bugs/

(Xcode is sometimes bugging 🙂)

**Comment by magonicolas** [comment]
Thanks for your help, It did work.
You don't have an iOs version? Or how should I adapt it?

**Comment by Dev1an** [comment]
I just added an iOS version of the framework. It is basically just another target but it uses the same code. Because the framework only depends on Foundation you can use it on all apple platforms and also on linux.
