### ISSUE TITLE
Playground does not compile in Xcode 11.5

### ISSUE THREAD

**Issue by seriyvolk83** [Dev1an/A-Star#8]
☝️

**Comment by Dev1an** [comment]
Does the compiler produce any error codes or logs? Please provide them. Otherwise it is hard to know what is happening.

**Comment by seriyvolk83** [comment]
The library is compiled well, but when I open the playground it shows the following:

<img width="1610" alt="image" src="https://user-images.githubusercontent.com/1122179/86533528-831bb300-beda-11ea-96c9-9b96796abe5e.png">

**Comment by Dev1an** [comment]
Either select and build the macOS framework (because the playground is set to run on macOS by default) or set the playground platform to iOS in the playground settings

**Comment by seriyvolk83** [comment]
It does not help. Check the video:
[VideoA*.mov.zip](https://github.com/Dev1an/A-Star/files/4874959/VideoA.mov.zip)

**Comment by Dev1an** [comment]
Ah yes there is a problem with the iOS target. You can try to use the macOS version in the meantime.
![image](https://user-images.githubusercontent.com/3158324/86533616-a7739180-bed2-11ea-88b7-f58033cf7380.png)

**Comment by seriyvolk83** [comment]
It's the same for both targets. But "clean" helps.
